var GameDefinitions = (function() {

	return {
		"beginner" : {
			"title" : "So Many Bricks",
			"image" : "levelManyBricks",
			"rows" : 5,
			"columns" : 9,
			"blocks" : [ 
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},

				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},

				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},


				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
			]
		},
		"e" : {
			"title" : "Internet Explorer",
			"image" : "levelExplorer",
			"rows" : 7,
			"columns" : 7,
			"blocks" : [ 
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},

				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},		

				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"}					
			]
		},
		"html" : {
			"title" : "HTML",
			"image" : "levelHtml",
			"rows" : 5,
			"columns" : 11,
			"blocks" : [ 
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},	

				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},					

				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},	

				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"}
			]
		},
		"8" : {
			"title" : "Windows 8",
			"image" : "levelEight",
			"rows" : 7,
			"columns" : 5,
			"blocks" : [ 
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},

				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},			

				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},

				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},

				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"}			
			]
		},
		"10" : {
			"title" : "IE 10",
			"image" : "levelTen",
			"rows" : 7,
			"columns" : 10,
			"blocks" : [ 
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},		
				
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},	

				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},

				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},

				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},	

				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "noBlock"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "block bounce"},
				{x: 0, y: 0, className: "noBlock"}
			]
		},			
		"beginner_test" : {
			"title" : "Test",
			"image" : "levelTen",
			"rows" : 1,
			"columns" : 1,
			"blocks" : [ 
				{x: 0, y: 100, className: "block bounce"}
			]
		},
		"beginner_test2" : {
			"rows" : 2,
			"columns" : 1,
			"blocks" : [ 
				{x: 0, y: 100, className: "block bounce"},
				{x: 0, y: 100, className: "block bounce"}
			]
		}
	}

}());



